### ISSUE TITLE
Large memory consumption

### ISSUE THREAD

**Issue by Artim96** [celzero/rethink-app#572]
Hey,
I was wondering if it was normal that the app is used really large amounts of system memory. In developer settings under memory, Android shows values between 1.7 and 2.5 GB of used memory (depending on the interval I set, with 1.7 GB showing at the 24 h interval and 2.5 GB showing at the 3 h interval). After force closing it, it goes back about 400 MB, which would be a much more sane amount. So the question is, is that a problem with the app or with the Android version I use.

I'm currently on Beta 1 of the quarterly Feature Drops of Android 13 on the Pixel 6. Maybe someone on Non-Beta Android 13 can take a look. If it's a problem with Android of course it would be ideal if Google could fix it before the version goes live. Of course if it's a problem with the app a fix would be appreciated too.
I can't say how it was before the beta though since I just recently switched from a similar app that got unusable for me.

**Comment by afontenot** [comment]
N.B. the Pixel 6 has 8 GB of RAM.

I can confirm this issue on Android 12 (LineageOS). In fact it seems to be responsible for most of the crashes I've been seeing. My device only has 4 GB of RAM.

An example crash:

Log excerpt:
```
09-22 21:07:45.465  1562 29913 I ActivityManager: Low on memory:
09-22 21:07:45.466  1562 29913 I ActivityManager:   fg     TOP   118644: org.thoughtcrime.securesms (pid 26506) top-activity
09-22 21:07:45.466  1562 29913 I ActivityManager:   vis    FGS  1869523: com.celzero.bravedns (pid 29259) service
09-22 21:07:45.466  1562 29913 I ActivityManager:                        com.celzero.bravedns/.service.BraveVPNService<=Proc{1562:system/1000}
09-22 21:07:45.466  1562 29913 I ActivityManager:   Free RAM:   258,356K
09-22 21:07:45.466  1562 29913 I ActivityManager:   Used RAM: 3,637,306K
09-22 21:07:45.466  1562 29913 I ActivityManager:   Lost RAM:   372,080K
09-22 21:10:26.680  1562  3056 I ActivityManager: Process com.celzero.bravedns (pid 29259) has died: prcp FGS
```

I started a call in Signal around 2 minutes prior to this. It's the fg app you can see in the log above. A lot of random background tasks get killed until finally RethinkDNS dies just under 3 minutes into the low memory condition. (There's nothing else in logcat to indicate the cause of the process death.)

Here is the process exit as recorded by `adb bugreport`:

```
        ApplicationExitInfo #1:
          timestamp=2022-09-22 21:10:26.682
          pid=29259
          realUid=10272
          packageUid=102A72
          definingUid=10272
          user=0
          process=com.celzero.bravedns
          reason=2 (SIGNALED)
          subreason=3 (TOO MANY EMPTY PROCS)
          status=9
          importance=125
          pss=0.88GB
          rss=750MB
          description=null
          state=empty
          trace=null
```

750MB RSS seems extremely high, probably indicating a leak. My guess is that Rethink gets killed on my phone well before it can hit the 2 GB level seen by the bug reporter.

**Comment by ignoramous** [comment]
> My device only has 4 GB of RAM.

Android is guilty of taking up half that... Then there's so many other System / Privileged apps that are exempt from OOM... 4Gs is just too... stringent ;)

> 750MB RSS seems extremely high

Yep, it was 190M in `v044`; then moved up to `300M` in one of the `v05x` releases. `700M`+ sounds ridiculous. Checking...

`TOO MANY EMPTY PROCS` indicates Rethink's being torpedoed by ActivityManager, for having "empty processes"? https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/am/OomAdjuster.java;drc=7d7ee57b4dbbe4723c19cf5308eee10d6c6cf2a6;l=1099

**Comment by ignoramous** [comment]
On my OnePlus, the resident set size (RSS) is `135M` and the app has been running for 2 days non-stop with DNS + Firewall.

```
    138,884K: com.celzero.bravedns (pid 16630 / activities)
```

I wonder if you folks have local blocklists enabled which has a leak (because blocklists are around `60M` in-memory and if there was a leak, then I can see how it'd reach `800M`+). If so, can you see if disabling local blocklists (and/or using remote blocklists instead), results in *lesser* RAM use?

**Comment by Artim96** [comment]
I am using the On-device block lists. And yes, I just killed the app again with way over 1 GB usage over the last 3 hours. 

hat exactly to you mean by remote block lists?

And I've never used perfetto. Depending on how self-explanatory it is I can see if I can share traces

**Comment by ignoramous** [comment]
> [W]hat exactly to you mean by remote block lists?

RethinkDNS+ (our resolver), but one can [deploy their own](https://github.com/serverless-dns/serverless-dns) or use a service like NextDNS, AdGuard DNS, ControlD etc).

> And I've never used perfetto. Depending on how self-explanatory it is I can see if I can share traces

You'd need a debug build of the app. I am looking but prefetto's `heap_profile` and `java_heap_dump` have been unhelpful so far. From `adb shell dumpsys meminfo com.celzero.bravedns` it is clear that with local-blocklists enabled, after changing the DNS upstream a few times, or pausing / resuming the Rethink firewall a few times, app's RSS balloons past `1G`.

**Comment by afontenot** [comment]
> it is clear that with local-blocklists enabled, after changing the DNS upstream a few times, or pausing / resuming the Rethink firewall a few times, app's RSS balloons past `1G`.

I have also discovered that simply disabling on-device blocklists causes the extra memory to be GCed immediately without making any other changes. PSS went from 1.3G → 0.2G.

Also, not sure if it's relevant, but on my device I usually see much higher PSS than RSS. This doesn't make sense, because PSS is supposed to be lower. The explanation seems to be that PSS counts "system" memory in its usage and RSS doesn't. I don't know what type of memory usage this is, exactly, but I'm reproducing the `meminfo` below:

In my testing so far, I have only seen OOM when there's also high RSS.

```
 App Summary
                       Pss(KB)                        Rss(KB)
                        ------                         ------
           Java Heap:     8536                          21992
         Native Heap:    10660                          11828
                Code:     4320                          35088
               Stack:      724                            732
            Graphics:     1616                           1616
       Private Other:   113992
              System:  1147686
             Unknown:                                  116232
 
           TOTAL PSS:  1287534            TOTAL RSS:   187488       TOTAL SWAP PSS:  1145221
```

**Comment by ignoramous** [comment]
Interesting, on my OnePlus, ~`776M` shows up in RSS:

```yml
 App Summary                                                                    
                       Pss(KB)                        Rss(KB)                   
                        ------                         ------                   
           Java Heap:    32656                          49248                   
         Native Heap:    40524                          41820                   
                Code:    42524                         138016                   
               Stack:     1732                           1740                   
            Graphics:    11236                          11236                   
       Private Other:   772976                                                  
              System:    13731                                                  
             Unknown:                                  776780                   
                                                                                
           TOTAL PSS:   915379            TOTAL RSS:  1018840       TOTAL SWAP PSS:      252

```

Also, the code-segment in my sample is high at `130M`. 

So: What I am doing is,

1. Kill Rethink
2. Start it back up with local-blocklists enabled.
3. Pause the app, and resume after 2 secs.
4. Flip DNS between `System DNS` and any other DNS.
5. Enable/Disable `Allow Bypass` twice or thirce.
6. `adb shell dumpsys meminfo com.celzero.bravedns`
